### ISSUE TITLE
Dear Sir, please use develop branch instead of master to lead your development well

### ISSUE THREAD

**Issue by GuptaAbhilasha** [incubus-playground/tamanoir-ui#4]
Dear Sir amalieiev,

My name is Abhilasha, and I'm from India. I have noticed that you use [GitHub](https://github.com) in a totally wrong way. You commit your changes into `master` branch directly. Oh... oh... oh... It is terrible approach! Dear Sir, you should read this very useful [acrticle](http://nvie.com/posts/a-successful-git-branching-model) to understand how `Git` and `GitHub` work. Please create a new `develop` branch and commit your changes there. And when your feature will be done merge it into the `master` branch. That is how we do development in India. Thank you for your patience, Sir.

Abhilasha

**Comment by amalieiev** [comment]
Hi, Abhilasha.
Thank you for this article, it was very useful.
Artem M.

2015-07-09 23:47 GMT+03:00 Abhilasha Gupta notifications@github.com:
